version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - mongodb_data:/data/db
  app:
      image: matchup-backend-image
      depends_on:
      - mongodb
      ports:
        - "8080:8080"
      environment:
        SPRING_DATA_MONGODB_URI: mongodb://root:example@host.docker.internal:27017/matchup?authSource=admin

volumes:
  mongodb_data: